# Generated by Django 3.2.18 on 2023-04-19 15:29

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_auto_20230302_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image_primary', models.ImageField(null=True, upload_to='')),
                ('image_secondary', models.ImageField(null=True, upload_to='')),
                ('image_tertiary', models.ImageField(null=True, upload_to='')),
                ('image_url_primary', models.URLField(null=True)),
                ('image_url_secondary', models.URLField(null=True)),
                ('image_url_tertiary', models.URLField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('listing_city', models.CharField(max_length=20)),
                ('listing_country', django_countries.fields.CountryField(max_length=20)),
                ('bedrooms', models.IntegerField()),
                ('max_occupancy', models.IntegerField()),
                ('amenities', models.CharField(choices=[('Dishwasher', 'Dishwasher'), ('Iron', 'Iron'), ('Washer & Dryer', 'Washer & Dryer'), ('Pool', 'Pool'), ('Jacuzzi', 'Jacuzzi'), ('Coffee Machine', 'Coffee Machine'), ('Garden', 'Garden'), ('Wifi', 'Wifi'), ('BBQ', 'BBQ'), ('Pizza Oven', 'Pizza Oven'), ('Smart TV', 'Smart TV')], max_length=200)),
                ('available_services', models.CharField(blank=True, choices=[('Housekeeping', 'Housekeeping'), ('Massage', 'Massage'), ('Food preparation', 'Food preparation'), ('Babysitting', 'Babysitting'), ('Airport Pickup', 'Airport Pickup')], max_length=200, null=True)),
                ('favourites', models.ManyToManyField(blank=True, related_name='favourite', to='members.Profile')),
                ('listing_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='members.profile')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(default='')),
                ('satisfaction', models.CharField(choices=[(1, 'Dream vacation'), (2, 'Excellent'), (3, 'Very good'), (4, 'Good'), (5, 'Not as expected'), (6, 'Bad experience')], max_length=50)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
    ]
