# Generated by Django 3.2.18 on 2023-04-19 19:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Dishwasher', 'Dishwasher'), ('Iron', 'Iron'), ('Washer & Dryer', 'Washer & Dryer'), ('Pool', 'Pool'), ('Jacuzzi', 'Jacuzzi'), ('Coffee Machine', 'Coffee Machine'), ('Garden', 'Garden'), ('Wifi', 'Wifi'), ('BBQ', 'BBQ'), ('Pizza Oven', 'Pizza Oven'), ('Smart TV', 'Smart TV')], max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='available_services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Housekeeping', 'Housekeeping'), ('Massage', 'Massage'), ('Food preparation', 'Food preparation'), ('Babysitting', 'Babysitting'), ('Airport Pickup', 'Airport Pickup')], max_length=200, null=True),
        ),
    ]
