# Generated by Django 3.2.18 on 2023-03-02 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('email_address', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('address_1', models.CharField(max_length=80, null=True)),
                ('address_2', models.CharField(max_length=80, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('postcode', models.CharField(max_length=12, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('group_size', models.PositiveSmallIntegerField(blank=True)),
                ('preferences', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Quiet Location'), (2, 'By the Sea'), (3, 'Swimming Pool'), (4, 'Pet Friendly'), (5, 'Family Friendly'), (6, 'Couples'), (7, 'City Life'), (8, 'Outdoor Space')], max_length=100)),
                ('is_host', models.BooleanField()),
                ('is_guest', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='../', upload_to='images/')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
