# Generated by Django 3.2.18 on 2023-03-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_profile_group_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_guest',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_host',
            field=models.BooleanField(null=True),
        ),
    ]
